services:
  blender:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        UV_SYNC_EXTRAS: "cpu"
    container_name: blender

    command: sleep infinity

    environment:
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      - PULSE_SERVER
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      - LIBVA_DRIVER_NAME=d3d12

    volumes:
      - /mnt/wslg:/mnt/wslg:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:cached
      - /usr/lib/wsl:/usr/lib/wsl:cached
      - ./:/home/blender/workspace
